### ISSUE TITLE
Update download link to OracleJDK8

### ISSUE THREAD

**Issue by exoego** [scala/scala-lang#1002]
Currently, https://www.scala-lang.org/download/ shows link to OracleJDK8
![image](https://user-images.githubusercontent.com/127635/52035754-7caf3c00-256e-11e9-8e57-4ed1095a6cd6.png)

[According to Oracle](https://blogs.oracle.com/java-platform-group/oracle-java-se-releases-faq), public  (free of charge) update ends January 2019 (today!!).

I think it is better to update it to OracleJDK11 and also provide links to OpenJDK:

* OpenJDK Installation page https://openjdk.java.net/install/
* AdoptOpenJDK https://adoptopenjdk.net
* Or similar alternatives

As far as I checked git history, source code does not include a link to OracleJDK8... weird... 
https://github.com/scala/docs.scala-lang/blob/33b79f9a29ece03aadc2d35d1198893d64a4f037/_layouts/downloadpage.html#L24-L27

**Comment by SethTisue** [comment]
> As far as I checked git history, source code does not include a link to OracleJDK8

you were in the wrong repo. I've transferred this ticket to the right repo.

> I think it is better to update it to OracleJDK11

we don't currently recommend JDK 11 as the default for newcomers. eventually we will able to do that, but I don't think that day is here yet, since it's not the most compatible choice. see https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

> According to Oracle, public (free of charge) update ends Jauary 2019 (today!!).

yeah.

so the following is probably debatable, let's discuss:

personally, I don't see a problem with continuing to recommend OracleJDK 8 to newcomers for now. it's true that going forward, it won't have the latest security updates, but that seems like a concern for people running production apps, not a concern that affects newcomers who are trying to learn the language.

**Comment by soronpo** [comment]
Lately I taught an academic course that a major part of it was a DSL written in Scala. All students were new to Scala and JDK11 caused issues (I haven't had a chance to investigate further yet). I think that until the entire community build works successfully with JDK11, there is no reason to change the recommendation above.

**Comment by smarter** [comment]
OpenJDK 8 and 11 are now officially maintained by Red Hat: https://www.redhat.com/en/about/press-releases/leadership-openjdk-8-and-openjdk-11-transitions-red-hat and they publish a JDK 8 installer for Windows: https://developers.redhat.com/products/openjdk/download. 

> I  don't see a problem with continuing to recommend Oracle's JDK 8 to  newcomers for now. it's true that going forward, it won't have the  latest security updates, but that seems like a concern for people  running production apps, not a concern that affects newcomers who are  trying to learn the language.

Strongly disagree. We should not recommend unmaintained software with known security issues, what if a remote code execution vulnerability is discovered in it one day ?
