### ISSUE TITLE
Add SlickEdit to IDE List?

### ISSUE THREAD

**Issue by danwhenry** [scala/scala-lang#1021]
SlickEdit is now a full featured Scala IDE including context tagging and a debugger.  Can it be added to the list of Scala IDEs on the home page?

Thanks,

Dan Henry

SlickEdit, Inc

**Comment by sjrd** [comment]
Hi @danwhenry. Thanks for reaching out.

There are two things that, a priori, make me reluctant to do so:

* From my bubble, I don't see SlickEdit as a popular IDE for Scala at the moment. I believe we reserve the front page for already established IDEs, so that beginners have a better chance to find help in the community afterwards.
* It seems SlickEdit does not have any free version (besides a Trial, which I guess is time-limited). So far all the IDEs we list are free or have a free version with a decent feature set.

Those two things combined make me think that listing SlickEdit---especially on the front page---would be closer to advertisement than to help for our community. I would need convincing arguments to be in favor of this.

**Comment by SethTisue** [comment]
I agree with Seb. In order to list SlickEdit, we'd need an appropriate place to put it, and right now we don't have one, because the front page isn't it.

You might be able to alter this PR to _make_ a place to put it. The front page could link to a dedicated page for listing IDE and editor support, and then there'd be room for all sorts of stuff on that page, including info on Metals and the Dotty IDE, info on plugins and modes for various editors, and a link to SlickEdit, too. This would require some work, some design work, and also some content-gathering. (The initial version of the page wouldn't need to be 100% complete, but it would need to have the basics in place.)

**Comment by SethTisue** [comment]
I've opened an issue (#1025) on my suggestion, perhaps a volunteer would like to tackle it.

**Comment by danwhenry** [comment]
·         OK.  Respectfully, is it because we do not have a large enough Scala following or because we do not have a free version?  Because we do not have a large Scala following because our extensive Scala support – including Context Tagging®, SmartPaste®, a fully integrated debugger and source code beautifier were just completed this version.  I swear I am not being belligerent, I just want to understand the entirety of the reasoning in case there is anything we can change that might get us up there with the other IDEs.
Thanks for your consideration,
Dan

**Comment by SethTisue** [comment]
> Respectfully, is it because we do not have a large enough Scala following or because we do not have a free version?

for me it's some of both, mostly the former.

one place I'd suggest you get the word out is https://users.scala-lang.org, a post announcing your Scala support there would be very much on-topic and appropriate

**Comment by danwhenry** [comment]
Thank you, Seth!

**Comment by olafurpg** [comment]
@danwhenry first of all, congratulation on releasing Scala support for SlickEdit! Having worked on editor tooling myself, I can imagine this milestone represents a lot of hard work and you are excited to get users :) I believe there is big demand for improved Scala editor tooling and I hope users will find your product helpful (the demos on your website look great!).

Here are some ideas how you could get the word out about your product

- post an announcement on r/scala and update the "Coding tools" sidebar to mention SlickEdit https://old.reddit.com/r/scala/
- tweet about your announcement
- share your announcement in https://users.scala-lang.org/

I would also recommend you update your website to explain how SlickEdit compares to IntelliJ. The website lists a lot of impressive features but for people coming from IntelliJ (which is by far the most widely used Scala editing tool) I suspect many are curious to know answers to questions like

- how fast are diagnostics/completions?
- are diagnostics reliable? Does SlickEdit show error for valid code or no errors for invalid code?

I also recommend you try to lower the barrier of entry for people trying out your product for the first time. I personally tried to install SlickEdit and gave up after several minutes of clicking through multiple installation forms to setup the free trial. It would great if users could try out SlickEdit without registering an email address or providing the SlickEdit application root access to their computers.

**Comment by storkinsj** [comment]
It sort of always boggles my mind that programs whom ostensibly make their entire living from building software... are the ones whom most often refuse to pay for it.

**Comment by SethTisue** [comment]
> The front page could link to a dedicated page for listing IDE and editor support

This is happening at https://github.com/scala/docs.scala-lang/pull/3042
