### ISSUE TITLE
Landing page is difficult to read on mobile

### ISSUE THREAD

**Issue by olafurpg** [scala/scala-lang#1102]
While browsing the scala-lang.org landing page on my phone (iPhone 11, Safari) I noticed that there are a bit too many editors in one horizontal row.

![scala-lang-landing](https://user-images.githubusercontent.com/1408093/71531265-2bc6d580-28ee-11ea-83dd-121c66fe0233.png)

It would be nice to either split those into multiple rows or remove some editors.

**Comment by olafurpg** [comment]
Originally reported by @tgodzik

**Comment by tgodzik** [comment]
Haven't checked it on mobile when adding the editors, so I will try to fix it there. Although, if anyone is more qualified I would welcome some help.

**Comment by SethTisue** [comment]
I think the Eclipse icon can now be dropped entirely. And should be dropped, and not just for layout reasons: maintenance has ceased and it doesn't support Scala 2.13.

The IntelliJ and VSCode icons should stay.

I think the other text editors could be collapsed into a single icon, but it isn't obvious what the icon and label ought to be.

I don't think it would be right to have "Metals" and a Metals icon, because newcomers would think that's an IDE they haven't heard of; we want to communicate, as well as we can given the space constraint, that users can keep using their favorite editor and get IDE-like features. So perhaps "Text Editors", and then link to a Metals page that lists what editors integration exists for?

**Comment by olafurpg** [comment]
Metals has a custom Eclipse plugin that could provide a migration path for Eclipse users https://scalameta.org/metals/docs/editors/eclipse.html

We're planning to drop Atom in Metals since the LSP support is incomplete and it looks like it's longer being actively developed.

It would be nice to keep Emacs, Vim and Sublime Text since those editors seem to be quite widely used. It would be best if we can do two rows I think.

I agree it's not necessary to mention "Metals" since the target audience of the landing page is outside the Scala community. Maybe mention instead something like "Other editors via Language Server Protocol (LSP)"?

**Comment by SethTisue** [comment]
(I'd be fine with two rows.)

**Comment by tgodzik** [comment]
I am trying to split this into two rows, but I am totally unfamiliar with the framework here. Any pointers to where find some documentation?

**Comment by tgodzik** [comment]
@SethTisue I think I got it, let me know if it's a sensible solution.

**Comment by SethTisue** [comment]
I don't know CSS; anyone else watching this repo able to review...?
