### ISSUE TITLE
Gitter vs Discord

### ISSUE THREAD

**Issue by vincenzobaz** [scala/scala-lang#1256]
The website links to gitter channels.
In the meanwhile Discord channels were open.
Should we consider replacing Gitter links to discord or at least adding the discord links?

**Comment by SethTisue** [comment]
https://www.scala-lang.org/community/ does have the Discord links — just not right at the top.

I think a pull request that increased the visibility of Discord on that page would not be controversial.

But in order to replace the Gitter links _entirely_, it would have to be decided at the org level that Discord is now our flagship chat platform. I don't believe that decision is made yet. (One notable holdout is @smarter, but I don't know how strong his opposition is.) The discussion of record on this subject is https://users.scala-lang.org/t/can-we-have-an-official-scala-discord-server/5157

If Discord _does_ become our flagship chat platform (I'm now in favor of that, after long holding a cautious/skeptical attitude about it), I think we should shut down all of our Gitter rooms, in order not to unnecessarily fragment the community. There will be a certain amount of opposition, but you can't please all the people all the time.

**Comment by smarter** [comment]
I don't plan to join discord (I have a PhD thesis to write and enough distractions as is), but I'm not against people using it.

**Comment by SethTisue** [comment]
"I believe it is now time for the Scala org to shut down its Gitter rooms and standardize on Discord" — me, this morning, at https://users.scala-lang.org/t/can-we-have-an-official-scala-discord-server/5157/59?u=sethtisue

**Comment by SethTisue** [comment]
@vincenzobaz I hope the Center will have an internal discussion about this? maybe after y'all Europeans aren't on your long vacations anymore :-)

**Comment by julienrf** [comment]
Hi @SethTisue,
The Scala Center team discussed that, and our conclusion is that it’s better to have a single chat platform. If the community effectively transitioned to Discord, that’s the platform we should link to in scala-lang.org. So:

> I think a pull request that increased the visibility of Discord on the community page would not be controversial.

:100:

**Comment by SethTisue** [comment]
@julienrf I want to make sure we're 100% clear about this, though: I am not only suggesting alterations to the community page. I am suggesting _actually shutting down_ the scala/* Gitter rooms. and I wouldn't do that without a very clear go-ahead from the Center (and after any discussion on the Discourse thread has died down)

**Comment by Ichoran** [comment]
For the record, I like Discord less than Gitter, and I don't think the fragmentation matters as long as which one to go first is clearly indicated from the web site.  Having a hardly-used Gitter site hasn't seemed to harm the Rust community at all.  If it were up to me, I'd leave Gitter up until the only things posting there were tumbleweeds.

But I also don't think it matters all that much, so I'll grudgingly go along with whatever.

**Comment by SethTisue** [comment]
@Ichoran for-the-record discussion on this goes on Discourse

**Comment by SethTisue** [comment]
fwiw, I wouldn't mind leaving scala/scala itself around, as long as moderation problems (either spam or CoC) don't develop. (I still look in on #scala on IRC daily even though it's 99% crickets.) Mild preference to shut it down, but I don't really care either way.

It's mainly the other rooms I actually do want to see shut down:
* scala/contributors, where the community is small so fragmentation is especially harmful
* scala/job-board, because it tends to consume moderator attention

**Comment by joshlemer** [comment]
I think we should just move officially to Discord now, no point having 2 chat rooms. In fact pointing users towards Gitter isn't without cost. I think leaves a bad impression, that Scala isn't keeping up with the times.
