### ISSUE TITLE
App + cats-effect hangs on 3.1.0 but works fine in 2.13.7

### ISSUE THREAD

**Issue by jmgimeno** [scala/scala-lang#1326]
This code
```scala
import cats.effect._
import cats.implicits._
import cats.effect.unsafe.implicits.global

object IOComposition extends App {
  val hello = IO(println(s"[${Thread.currentThread.getName}] Hello"))
  val world = IO(println(s"[${Thread.currentThread.getName}] World"))
  val hw1: IO[Unit] = for {
    _ <- hello
    _ <- world
  } yield ()
  val hw2: IO[Unit] =
    (hello, world).mapN((_, _) => ())
  hw1.unsafeRunSync()
  hw2.unsafeRunSync()
}
```
hangs with Scala 3.1.0 after printing only "Hello"
```
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
[io-compute-2] Hello
```
but works perfecty with Scala 2.13.7
```
Compiling project (Scala 2.13.7, JVM)
Compiled project (Scala 2.13.7, JVM)
[io-compute-2] Hello
[io-compute-4] World
```
Also opened in cats-effect as https://github.com/typelevel/cats-effect/issues/2748

**Comment by SethTisue** [comment]
This is the issue tracker of the Scala website, not of the Scala language. If you want to report a bug in Scala 3, that's https://github.com/lampepfl/dotty/issues

But actually, I think you should hold off on opening a ticket there. You should wait until you or the cats-effect come up with solid evidence that a Scala bug is actual the root cause of the hang you are experiencing.
