### ISSUE TITLE
aiggh, nulls on our homepage!

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#349]
reported by @misto at https://twitter.com/m_st/status/661516299126890496

![aigh!](https://pbs.twimg.com/media/CS4tkYPWEAA-WbV.png:large)

**Comment by SethTisue** [comment]
@fsalvi is this something you could tackle? it looks like this line in `resources/js/main.js`:
 
    '<div class="training-trainers-name"> By '+training.trainers+'</div>' +

needs a null check

**Comment by fsalvi** [comment]
I guess the problem is on the typesafe webpage, we are using this json file:
http://www.typesafe.com/subscription/training.json

eg:
{"where":"Virtual only","when":"Nov 18 2015","trainers":null,"organizer":"BoldRadius","status":"live","url":"http://boldradius.com/detail/VWc7ty4AAC0AsXjS/advanced-akka-with-scala"}]}
