### ISSUE TITLE
Is an "overhaul" in the works?

### ISSUE THREAD

**Issue by vossad01** [scala/scala-lang#581]
I have seen a number of distributed references to a potentially major changes coming to the website.  Is this actually planned?  Is there any way to bring such a plan into the public light?

Contributors may be hesitant to work on the current scala-lang if it is likely to be superseded by a new version.  Since nothing is tracking what is planned for a new version, they cannot see if their change is consistent with the future direction of the website or get involved on the planned changes.

**Citations:** (not exhaustive)
https://github.com/scalacenter/scaladex/issues/304#issuecomment-265250066
> @heathermiller: Adding this to my list of todos for the next scala-lang update (soon).

https://github.com/scala/scala-lang/pull/558#issuecomment-264692979
> @jarrodwb: Maybe we can address this when we do a complete overhaul of the site?

[SCP-008: Maintain scala-lang, docs.scala-lang, scala.epfl.ch websites](https://github.com/scalacenter/advisoryboard/blob/master/proposals/008-websites.md) was approved.

**Comment by jarrodwb** [comment]
Thanks for bringing this up. I don't have any more information to share on the topic.

Hopefully we can get a reboot of the site in the works. I suspect it is just a matter of time and prioritization. The new year is just around the corner. :+1: 

If there is anything I can do to help please let me know. I am still getting settled in Hamburg at the moment but I can find time soon help out.

**Comment by heathermiller** [comment]
Hi @vossad01, thanks for asking. I'm not sure a GitHub issue is the most appropriate place to ask this question, because this isn't really a specific _issue_ with the site that can be _fixed_. It's more of a question/discussion that would probably be best placed on Discourse.

In any case, the answer is yes, as of right before Christmas, concrete plans were made and tentative dates/deliverables were agreed upon with 47 Degrees, who will help us with some of the larger website-related tasks. Details are still being worked out–in particular, the most difficult/time-consuming stuff, or stuff that needs help from a professional (like making the website responsive, which is more difficult than it appears) will be done by 47 Degrees.

Work on scala.epfl.ch and inner pages + blog of scala-lang will also be done, and then we can port some of these layouts to the doc site. 

Like I said, we're currently discussing right now, attempting to prioritize so that stuff that is hardest/needs professional help is done by a professional designer + professional front end folks. That's not all totally finished yet. When it is, I'm happy to share the stuff 47 Degrees will do. (We're doing this in steps, right now we're focused on the front page of scala-lang, next we'll switch to the inner pages + blog of scala-lang, etc)

**Comment by SethTisue** [comment]
So contributors shouldn't currently embark on an ambitious site overhaul (or even just look & feel overhaul), but it's very much still safe and encouraged to contribute pretty much any other kind of incremental change. Nothing will get lost. (SCP-008 strongly emphasizes incremental change.)

Of course, it's always a good idea to discuss any sweeping or potentially controversial change in advance before sinking a lot of work into it.

**Comment by vossad01** [comment]
**The issue:** As a potential contributor, I suspect it is not worth my time to contribute to the project because the project is not open about its plans.  Some evidence suggests that my contributions would be moot because major changes have been suggested.  Not mentioned in OP, I further know there were issues in the past surrounding this particular project that lead to a fork of moderate success further adding hesitation to getting involved.

**A possible fix:**  Provide information on what is going on.  Decide if being more open about plans aligns with the in the goals/intentions of the project.

See also: https://contributors.scala-lang.org/t/lets-close-this-discourse-instance/300/13

**Comment by SethTisue** [comment]
I think SCP-008 and the advisory board minutes where it was discussed, is very open and clear about exactly what's going on. A draft of SCP-008 was discussed in public well in advance of the meeting; scala_lang tweeted about it.

I honestly don't see what could have been done better or more openly here...?

**Comment by SethTisue** [comment]
P.S. I don't think your characterization of Simon's fork is accurate, but I don't think we should re-litigate that on this ticket, either.

**Comment by vossad01** [comment]
@SethTisue All of the things you mentioned happened outside of this GitHub project.  Effectively, if a user that wants to participate on this project they need to learn about and plug into a broader Scala community or risk not being informed.  If a user wants that level of commitment, it is great that a community is there.  However, my minority opinion is that it is too high of commitment and makes a barrier that is intractable for some.  If someone wants me to I can explain the difficulties of this I will.

> I honestly don't see what could have been done better or more openly here...?

I'm trying not to be prescriptive in how the issue tracker is used and there is a lot of variation, but here are some ways I can think of that would have provided more information:
 - Heather's referenced list of todo's could have been a GitHub issue that was then referenced on the Scaladex issue.
 - Discussion on SCP-008 could have been opened here or cross referenced with an issue here, or mentioned on particular issues here that were in mind when drafting SCP-008.
 - The referenced "tentative" plans/deliverables, could be listed as Issue(s)

I am not saying any of these have found the Right Way™ of managing GitHub issuse, put here is perhaps some inspiration:
 - [You no longer need to follow a blog to see what is happening with .NET languages and it is more transparent to boot](https://github.com/dotnet/roslyn/labels/Design%20Notes)
 - Right now is a bad example because there is not an active iteration plan, but if I want to know what is happening with VS Code I just need to look at what is in the works [iteration plan](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20plan%20label%3Aiteration-plan) to see what is currently active and the [draft iteration plan](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+plan+label%3Aiteration-plan-draft) to see what is in the pipe
 - [This popular Android App encourages explicitly encourages discussions on some if its issues](https://github.com/iSoron/uhabits/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion)
 - [NativeScript is a very friendly to questions on its issue tracker.](https://github.com/NativeScript/nativescript/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AT%3AQuestion%20)  Personally I think it is a little more permissive than ideal, but from what I have seen they are always friendly, and I know from experience that extends to questions that arise when trying to contribute.
 - In addition to labels as the above projects use many projects utilize Milestones for some related purposes. 

None of the above examples are demonstrating use of Milestones, but I have also seen those used successfully.

@SethTisue has let me know there is more history with Simon's fork that I was not aware of which so I removed the remark to try to stay out of it.  However, that does goes to support how complex it is to know what is and has gone on and how that impacts approachability.

**Comment by SethTisue** [comment]
Thanks, that helps me understand your thinking better.

A lot of what you've written is about how communication is handled in the Scala open source effort generally, spanning multiple repositories. I'm only going to respond to the part that I see as specifically being about this repository in particular.

> Effectively, if a user that wants to participate on this project they need to learn about and plug into a broader Scala community or risk not being informed

I'm actually totally comfortable with that. I really don't think this repo is active enough to exist as in independent community. The number of contributors, not counting little drive-by fixes, is small. The number of people even watching this repo, and therefore reading this, is quite small! This repo doesn't have its own Gitter room, and so on. It's intentional that most of the communication around the overall direction of this repo happens in general Scala forums like scala-internals/scala-debate/Discourse, Gitter rooms like scala/contributors and scala/center, the scala_lang twitter account, and so forth, because the Scala website concerns the entire Scala community, and because we hope to attract contributors by taking about these things _in the places where people already are_.

If we want activity in this repo to increase, my intuition is that making this repo _more_ separate from the rest of the community, as you seem to be suggesting (?), would probably hurt, not help.

So that's my take on this repo. On the broader issues, I'm happy to engage elsewhere.

**Comment by vossad01** [comment]
@SethTisue Thank you for this.  I think your post is probably the clearest explanation on the difference of opinion.  I think your view is valid and makes sense.

> we hope to attract contributors by talking about these things _in the places where people already are_.

Where my opinion is different is that I am not sure that same people that are in those other discussions are also those most likely to be active in maintaining a website.  The same people that like discussing intricacies of a language and its designs, or are great at hacking Scala code, may not be the same ones wanting to maintain a website and engage in those sorts of marketing activities that are likely a user's first exposure to Scala.  Having watched the website for many years I do not believe it has kept pace with the growth of the Scala ecosystem by its contributors during that time, but I would not fault contributors for that.

Since there will now be dedicated resources towards the website, hopefully things will largely take resolve themselves.

**Comment by SethTisue** [comment]
I hope so!

One more thought about the “where people already are” thing — I think the site could certainly do a much better job of recruiting _the site visitors themselves_ to help out. So e.g. https://github.com/scala/scala-lang/issues/62, which I hope will get attention. (Note that an interested contributor could make targeted improvements in this area now or any time, it doesn't actually need 47 Degrees or whoever.)
