### ISSUE TITLE
Make Scala in a nutshell bullets more prominent

### ISSUE THREAD

**Issue by ashawley** [scala/scala-lang#643]
After visiting the Scala Web site for 2 years, I hadn't noticed you could click on the "bullets" on the main page to uncover Scala code examples ("Seamless Java interop", "Type inference", "Concurrency & distribution", "Traits", "Pattern matching", "Higher-order functions").

Is there a way to make these more prominent?  Doesn't look like the redesign changed them much in #606 (although font contrast _is_ better).  Maybe there's a user interface trick that could hint that that you need to click on them.   Or maybe they could just be entirely rethought.  Currently, "click the boxes below to see Scala in action! " in 12 pixel font in lower contrast colors and the background color changing on hover is not making it obvious.

I don't have any suggestions, but given the defect in the concurrency example in #641, it seems I'm not the only one missing them.  Enabling Tut, see #639, might fix the deprecated code problem, but I'm pretty sure visibility is also a problem.  They're worth making more visible, IMO.

**Comment by SethTisue** [comment]
> After visiting the Scala Web site for 2 years, I hadn't noticed you could click on the "bullets" on the main page to uncover Scala code examples

omg, me either, I had no idea.

part of the problem is that even if you get the idea to click, then after you click one of them, the thing that appears is waaaaaay below where you clicked, so it might not even be on the screen. when I tried it at first, I thought the site was broken, and it took me a little while to figure out what was happening. so for example:

![screen shot 2017-05-01 at 8 44 28 am](https://cloud.githubusercontent.com/assets/161079/25584339/75a386a4-2e4a-11e7-8ba3-3ce9fa1cd721.png)

I've clicked on "Higher-Order Functions" and it has expanded, but if I didn't have "Higher Order Functions" scrolled pretty high on the screen, I wouldn't be able to see the little triangle indicating it had expanded, and unless it's reeeeeeeally high on the screen, I can't see what it expanded to.

**Comment by ashawley** [comment]
> even if you get the idea to click, then after you click one of them, the thing that appears is waaaaaay below where you clicked

Yikes.  Is that with the current site, or the redesign?  Hopefully, that doesn't exist in the redesign.

**Comment by SethTisue** [comment]
> Hopefully, that doesn't exist in the redesign

Oh. I should have checked. It's much better in the redesign. (I've deleted most of my comment.)

**Comment by travissarles** [comment]
I noticed this issue as well. It is better with the latest design but it's still not as obvious as it could be. Next time we do another design makeover, this should be a priority.

**Comment by SethTisue** [comment]
maybe just adding a little "more..." link to each one would do it

**Comment by travissarles** [comment]
I'm going to ask a designer friend about this one...

**Comment by ashawley** [comment]
> maybe just adding a little "more..." link to each one would do it

Or, god forbid, just open the first bullet by default...

**Comment by travissarles** [comment]
I just tried opening the first bullet and it clutters the page even more. I'll experiment with a `+`

**Comment by SethTisue** [comment]
new design has "click the boxes below to see Scala in action!"
