### ISSUE TITLE
add minimal information about using RVM to get the right Ruby version

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#694]
for Ruby numbskulls like me, this could be a significant getting-started barrier to contributing

at #693 @ashawley suggested being a little less picky about the Ruby version, but @heathermiller  says RVM is the way to go. that sounds plausible, but could someone who knows this stuff a little add a little guidance to the readme?

**Comment by SethTisue** [comment]
fwiw, I was able to get going using http://docs.railsbridge.org/installfest/osx_rvm

**Comment by SethTisue** [comment]
(this repo could use a version of https://github.com/scala/scala.github.com/pull/784)

**Comment by ashawley** [comment]
I'm a Ruby numbskull as well.  There was info on rbenv added in #648, which is what I use.  I assume rvm is the same difference, but I wouldn't know for sure.

**Comment by SethTisue** [comment]
oh boy, I forgot that rbenv existed and/or that rvm and rbenv were different things.

@heathermiller is either acceptable?

**Comment by heathermiller** [comment]
Yeah, so I am also a Ruby numbskull. RVM seems to be the widely-accepted Ruby version management tool. Though rbenv is gaining traction ([citation](https://blog.metova.com/choosing-a-ruby-version-management-tool)). 

The instructions in the README about using rbenv are perfectly fine. Since this article I linked to suggests rbenv as a lighterweight alternative to RVM, we might as well keep the instructions in the README. Both RVM and rbenv serve the same purpose, so we should be good.

**Comment by heathermiller** [comment]
@SethTisue please reopen if you think there's something we still should do about this (that is, the instructions in the current README suggesting to use rbenv to make sure one is on the correct version of Ruby seem fine)

**Comment by SethTisue** [comment]
lol https://twitter.com/whereistanya/status/900244958707404801
