### ISSUE TITLE
Getting Started link in footer is different from the other

### ISSUE THREAD

**Issue by Philippus** [scala/scala-lang#774]
there are two links to 'Getting Started'.
One is from the footer which points to: http://www.scala-lang.org/documentation/getting-started.html
And one is through 'Documentation' -> 'Getting Started' which points to http://docs.scala-lang.org/getting-started.html
which one is correct?

**Comment by akrisanov** [comment]
I just started to learn Scala and decided to read the official website first. I found `Documentation` block in the https://www.scala-lang.org/ footer:

![image](https://user-images.githubusercontent.com/238505/33798136-dce6e7fc-dd13-11e7-9817-ca8227faeec8.png)

That link points on [Getting Started](http://www.scala-lang.org/documentation/getting-started.html) page where I was finishing step-by-step tutorials. One of them ([Building A Scala Project With Intellij And Sbt](http://www.scala-lang.org/documentation/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.html)) has a wrong sentence about existing code:

```
In the code, change currentYear - 1 to currentYear - 2 and look at the updated output in the console.
```
instead of
```
In the code, change 75 to 61 and look at the updated output in the console.
```

I think the problem is in having two different tutorial links. I can assume that both documentations http://docs.scala-lang.org/getting-started.html and https://www.scala-lang.org/documentation/getting-started.html have none sync state and maintained separately.
