### ISSUE TITLE
No VS Code or Emacs suggestions in "IDEs for Scala" section in front page of https://www.scala-lang.org/

### ISSUE THREAD

**Issue by victe** [scala/scala-lang#904]
That section shows only: IntelliJ, Sublime, Atom and Eclipse.
VS Code and GNU Emacs are as good as Sublime and Atom. All of them need Ensime.

**Comment by heathermiller** [comment]
I think VS Code is definitely worth mentioning. Emacs though; everyone who already uses Emacs (or Vim) typically don't need help to be aware that there exists plugins for their text editor. The CS bachelors' and masters' students that I have taught at Northeastern and EPFL tend to avoid Emacs and Vim these days in favor of editors like VS Code, Sublime, and Atom. That said, I think we should cater more towards VS Code/Atom/Sublime on the front page, since this is the direction that people seem to be going nowadays (professional developers and newcomers alike)

**Comment by SethTisue** [comment]
agree that should be addressed somehow.

because it's the front page, it should be done in a way that doesn't use up too much screen real estate or create too much distraction by presenting too many options. so I agree with:

> we should cater more towards VS Code/Atom/Sublime on the front page

but I do think there's room to at least link to information about other options in the smaller print.

in short, pull request welcome!
