### ISSUE TITLE
Events not updating

### ISSUE THREAD

**Issue by Philippus** [scala/scala-lang#905]
Right now there's an 'old' event on the website, I think it's because it is only refreshed after a successful build. If that is the reason Travis CI could be set up to run the build daily.

**Comment by SethTisue** [comment]
I have enabled a daily run at https://travis-ci.org/scala/scala-lang/settings

we see at https://travis-ci.org/scala/scala-lang/builds/388968739 that the build is failing with broken links

https://trends.google.com/trends/explore?date=all&q=scala%20tutorial is a 429. we should exclude the domain from checking

http://scalameta.org/scalafmt/#Configuration is 404, which I've reported to https://github.com/scalameta/scalafmt/issues/1219 . if it isn't fixed in the next few days we could remove the link or exclude it from checking

**Comment by SethTisue** [comment]
the daily Travis-CI run won't help with this, because it's actually https://scala-webapps.epfl.ch/jenkins/view/All/job/production_scala-lang.org-builder/ that publishes the site . regardless, I'll leave the daily run enabled, it will give us notice on broken links

**Comment by SethTisue** [comment]
somewhat to my surprise, I have the rights to change that Jenkins' job's configuration, so I added `@daily` to the build triggers
