### ISSUE TITLE
Nightly docs for 2.13 unlinked; 2.12 and 2.13 nightly docs are outdated

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#929]
- https://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/ is not linked from https://docs.scala-lang.org/api/all.html
- it doesn't seem to reflect the 2.13 APIs — for instance https://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/scala/index.html still has `type Seq[+A] = scala.collection.Seq[A]`.

@SethTisue asked for a ticket on Gitter, here it is.

**Comment by SethTisue** [comment]
labeled "good first issue" since the first bullet should be a quick fix. we can remove the label if just that part gets fixed

**Comment by SethTisue** [comment]
as for the second bullet, the 2.13 docs shown are from January 31, 2018, which iirc correctly is around when we moved publishing of nightlies off Jenkins and onto Travis-CI. 2.12 is affected equally.

I see from looking at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-release-website-update-api/ that the script that used to actually do the work is `scripts/jobs/release/website/update-api` in https://github.com/scala/scala-dist . @lrytz I guess this was an oversight that that script apparently isn't wired up right anymore...?

although the API docs are published to scala-lang.org, the repo where this problem is actionable is actually https://github.com/scala/scala; the `.travis.yml` there needs updating to do the job that https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-release-website-update-api/ used to do. looking at that Jenkins job, it seems that `scripts/jobs/release/website/update-api` in the scala/scala repo is where the actual work was done. (looking at `scripts/travis-publish-spec.sh` might be relevant too.)

**Comment by SethTisue** [comment]
I don't think we still have a goal of publishing Scaladoc for nightlies, since it doesn't change that often.

Maybe Scala 3 does it? Not a goal for Scala 2, in any case.
